import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'Recur Club',
    logo: '/images/careers/recurclub_logo.jpeg',
    location: 'Gurgaon, India',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2023-06',
    end_date: null,
    industry: 'Fintech',
    link: 'https://www.recurclub.com/',
  },
  {
    position: 'Frontend Developer',
    company: 'Binaryveda',
    logo: '/images/careers/binaryveda_logo.jpeg',
    location: 'Mumbai, India',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2022-02',
    end_date: '2023-05',
    industry: 'IT Services and IT Consulting',
    link: 'https://www.binaryveda.com/',
  },
  {
    position: 'Frontend Developer',
    company: 'RAZRCORP | XUPPI',
    logo: '/images/careers/razr_corp_logo.jpeg',
    location: 'Mumbai, India',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-03',
    end_date: '2022-02',
    industry: 'wellness',
    link: 'https://razrcorp.com/',
  },
  {
    position: 'Frontend Developer | Internship',
    company: 'Digital Media Hawk Private Limited',
    logo: '/images/careers/dmediahawk_logo.jpeg',
    location: 'Mumbai, India',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: '2021-03',
    industry: 'Advertising Services',
    link: 'https://www.linkedin.com/company/dmediahawk/',
  },
];
